Repository okaryo/TabTabTab, pull requests merged in 2023-07, with the labels that each got.

#69 Enable Arrow-Key-Selection and Enter-Key-Navigation in tab search results
  src/view/features/popup/components/Header.tsx
  src/view/features/popup/components/TabItem.tsx
  src/view/features/popup/pages/Home.tsx
Labels: enhancement

#70 Generate release note on tag push
  .github/workflows/generate-release-note.yml
Labels: development

#73 Improve search field visibility
  src/view/features/popup/components/Header.tsx
Labels: enhancement

#74 Enable window navigation in popup using right and left arrow keys
  src/view/features/popup/pages/Home.tsx
Labels: enhancement

#75 Translate to Korean
  dist/_locales/ko/messages.json
Labels: translation

#85 Fixed issue where no results were displayed when search returned zero matches
  src/view/features/popup/components/SearchResult.tsx
  src/view/features/popup/components/WindowTabs.tsx
  src/view/features/popup/pages/Home.tsx
Labels: bug

#86 Circular selection in tab search results with arrow keys
  src/view/features/popup/components/SearchResult.tsx
Labels: enhancement

#88 Ensure selected tab by arrow keys in search results is always visible
  .eslintrc.js
  src/view/features/popup/components/SearchResult.tsx
  src/view/features/popup/components/TabItem.tsx
  src/view/features/popup/pages/App.tsx
  src/view/features/popup/pages/Home.tsx
Labels: enhancement

#90 Sync open/close states between browser groups and popup
  src/model/GroupedTabs.ts
  src/model/Tabs.ts
  src/model/Window.ts
  src/model/Windows.ts
  src/repository/TabGroupRepository.ts
  src/repository/WindowsRepository.ts
  src/view/features/popup/components/GroupedTabList.tsx
  test/model/GroupedTabs.test.ts
  test/model/Tabs.test.ts
  test/model/Window.test.ts
Labels: enhancement

#91 Show tab count on group and pin headers
  src/view/features/popup/components/GroupedTabList.tsx
  src/view/features/popup/components/PinnedTabList.tsx
  src/view/features/popup/components/ThemeProvider.tsx
Labels: enhancement

#98 Improve tab group name text visibility in dark mode
  src/view/features/popup/components/GroupedTabList.tsx
Labels: enhancement

#99 Fix app bar design when popup width is large
  src/view/features/popup/components/GroupedTabList.tsx
  src/view/features/popup/components/Header.tsx
  src/view/features/popup/components/ThemeProvider.tsx
Labels: enhancement

#100 Refactor codes to prepare for Drag & Drop
  src/background/TabActivityTracker.ts
  src/model/GroupColor.ts
  src/model/GroupId.ts
  src/model/GroupedTabs.ts
  src/model/NestedTabs.ts
  src/model/PinnedTabs.ts
  src/model/Tab.ts
  src/model/TabGroup.ts
  src/model/TabId.ts
  src/model/Tabs.ts
  src/model/Window.ts
  src/model/WindowId.ts
  src/model/Windows.ts
  src/repository/TabGroupRepository.ts
  src/repository/TabsRepository.ts
  src/repository/WindowsRepository.ts
  src/view/features/popup/components/GroupedTabList.tsx
  src/view/features/popup/components/PinnedTabList.tsx
  src/view/features/popup/components/SearchResult.tsx
  src/view/features/popup/components/TabActionMenu.tsx
  src/view/features/popup/components/TabFavicon.tsx
  src/view/features/popup/components/TabItem.tsx
  src/view/features/popup/components/TabList.tsx
  src/view/features/popup/components/WindowTabs.tsx
  src/view/features/popup/hooks/useCloseTab.ts
  test/factory/TabFactory.ts
  test/model/GroupColor.test.ts
  test/model/GroupId.test.ts
  test/model/GroupedTabs.test.ts
  test/model/PinnedTabs.test.ts
  test/model/TabGroup.test.ts
  test/model/TabId.test.ts
  test/model/Tabs.test.ts
  test/model/Window.test.ts
  test/model/WindowId.test.ts
Labels: maintenance

#113 Enable showing tabs even when a page is still loading
  src/model/Tab.ts
  src/repository/WindowsRepository.ts
Labels: refinement

#117 Fix the incorrect tab count displayed beside the window tab
  src/view/features/popup/components/WindowTabs.tsx
Labels: bug
