Repository okaryo/TabTabTab, pull requests merged in 2025-01, with the labels that each got.

#487 Enable to Search Tabs in Dashboard
  src/presentation/views/options/components/Header.tsx
  src/presentation/views/popup/components/SearchResult.tsx
Labels: feature

#494 Enable keyboard navigation in the tab search dialog on dashboard
  dist/_locales/bg/messages.json
  dist/_locales/de/messages.json
  dist/_locales/en/messages.json
  dist/_locales/en_GB/messages.json
  dist/_locales/en_US/messages.json
  dist/_locales/fr/messages.json
  dist/_locales/ja/messages.json
  dist/_locales/ko/messages.json
  dist/_locales/pl/messages.json
  src/i18n/Translations.ts
  src/presentation/views/options/components/Header.tsx
  src/presentation/views/options/components/TabSearchForm.tsx
  src/presentation/views/popup/components/SearchResult.tsx
Labels: refinement

#495 v2.38.1
  dist/manifest.json
Labels: release

#499 Added Persian Translation
  dist/_locales/fa/messages.json
Labels: translation

#508 Add `pull_request` event trigger to run ci workflow
  .github/workflows/ci.yml
Labels: maintenance

#505 Setup toolbar icon behavior, so that opening dashboard works
  dist/manifest.json
  src/background/ToolBarAction.ts
  src/data/repository/ToolbarRepository.ts
Labels: bug

#510 v2.38.3
  dist/manifest.json
  package.json
  vite.config.ts
Labels: release

#517 Add CONTRIBUTING.md
  CONTRIBUTING.md
  docs/load_local_extension.png
Labels: documentation

#518 fix image path in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
